config/routes.rb
Rails.application.routes.draw do

  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "patients#index"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/field.rb
class Field < ApplicationRecord
  belongs_to :patient
  belongs_to :field_type
end

app/models/field_type.rb
class FieldType < ApplicationRecord
    has_many :fields, dependent: :destroy
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :fields, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  
  def new
    @patient = Patient.new
  end

  def create
      @patient = Patient.new(params.require(:patient).permit(:first_name, :middle_name, :last_name, :date_of_birth, :status, :address, :city, :state, :zip_code))
      @patient.save
      redirect_to patient_path(@patient)
  end
  
  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient.update(params.require(:patient).permit(:first_name, :middle_name, :last_name, :date_of_birth, :status, :address, :city, :state, :zip_code))
      flash[:success] = "Patient updated!"
      redirect_to patient_path(@patient)
    else
      flash.now[:error] = "Patient update failed"
      render :edit
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    redirect_to patients_path
    @patient.destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinniEmr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/patients/edit.html.erb
<h1>Edit patient</h1>

<div class="container">

    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@patient) do |f| %>

            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: "form-control" %>

            <%= f.label :middle_name %>
            <%= f.text_field :middle_name, class: "form-control" %>

            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: "form-control" %>

            <%= f.label :date_of_birth %>
            <%= f.text_field :date_of_birth, class: "form-control" %>

            <%= f.label :status %>
            <%= f.text_field :status, class: "form-control" %>

            <%= f.label :address %>
            <%= f.text_field :address, class: "form-control" %>

            <%= f.label :city %>
            <%= f.text_field :city, class: "form-control" %>

            <%= f.label :state %>
            <%= f.text_field :state, class: "form-control" %>            

            <%= f.label :zip_code %>
            <%= f.text_field :zip_code, class: "form-control" %>

            <%= f.submit "Save", class: "btn btn-primary" %>
        <% end %>

    </div>


</div>

app/views/patients/index.html.erb
<h1>Patients</h1>

<%= link_to "New patient", new_patient_path, class:"btn btn-primary" %>

<table id="patients-datatable" class="table table-striped table-sm">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Middle Name</th>
            <th>Last Name</th>
            <th>Date of Birth</th>
            <th>Status</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Zip Code</th>
        </tr>
    </thead>
    <tbody>
        <% @patients.each do |patient| %>
            <tr data-link= "<%= patient_path(patient) %>">
                <td><%= patient.first_name %></td>
                <td><%= patient.middle_name %></td>
                <td><%= patient.last_name %></td>
                <td><%= patient.date_of_birth.strftime("%m/%d/%Y") %></td>
                <td><%= patient.status %></td>
                <td><%= patient.address %></td>
                <td><%= patient.city %></td>
                <td><%= patient.state %></td>
                <td><%= patient.zip_code %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/patients/new.html.erb
<div class="container">

    <div class="col-md-6 col-md-offset-3">
        <%= form_with model: @patient do |f| %>

            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: "form-control" %>

            <%= f.label :middle_name %>
            <%= f.text_field :middle_name, class: "form-control" %>

            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: "form-control" %>

            <%= f.label :date_of_birth %>
            <%= f.text_field :date_of_birth, class: "form-control" %>

            <%= f.label :status %>
            <%= f.text_field :status, class: "form-control" %>

            <%= f.label :address %>
            <%= f.text_field :address, class: "form-control" %>

            <%= f.label :city %>
            <%= f.text_field :city, class: "form-control" %>

            <%= f.label :state %>
            <%= f.text_field :state, class: "form-control" %>            

            <%= f.label :zip_code %>
            <%= f.text_field :zip_code, class: "form-control" %>

            <%= f.submit "Save", class: "btn btn-primary" %>
        <% end %>

    </div>


</div>

app/views/patients/show.html.erb
<h1>Patient: <%= @patient.first_name + " " + @patient.middle_name + " " + @patient.last_name %></h1>
Date of birth: <%= @patient.date_of_birth.strftime("%m/%d/%Y") %><br>
Status: <%= @patient.status %><br>
Address: <%= @patient.address %><br>
City: <%= @patient.city %><br>
State: <%= @patient.state %><br>
Zip Code: <%= @patient.zip_code %><br>
<% fields = @patient.fields %>
<% fields.each do |field| %>
    <%= field.field_type.title %>: <%= field.content %><br>
<% end %>

<%= link_to "Edit patient", edit_patient_path(@patient), class:"btn btn-secondary" %><br>
<%= button_to "Delete patient",
              patient_path(@patient.id),
              method: :delete,
              form: { data: { turbo_confirm: "Are you sure?" } },
              class: "btn btn-danger" %>